---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "hosts.yaml"
    group_file: "groups.yaml"
runner:
  plugin: threaded
  options:
    num_workers: 20
logging:
  enabled: false
defaults:
  connection_options:
    netmiko:
      extras:
        timeout: 30
        conn_timeout: 10
        session_timeout: 60