# Network device inventory
devices:
  - name: s1
    host: 192.168.121.101
    username: admin
    password: admin
    device_type: cisco_ios
  - name: s2
    host: 192.168.121.102
    username: admin
    password: admin
    device_type: cisco_ios
